# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

maxEE <- function(x) {
    .Call('_RreadQC_maxEE', PACKAGE = 'RreadQC', x)
}

Qstat <- function(x) {
    .Call('_RreadQC_Qstat', PACKAGE = 'RreadQC', x)
}

